language: python
python:
  - "2.7"
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
install:
 - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
